# Generated by Django 5.1.1 on 2024-10-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Lagos', 'Lagos'), ('Abuja', 'Abuja'), ('Ibadan', 'Ibadan'), ('Ondo', 'Ondo'), ('Ekiti', 'Ekiti'), ('Ogun', 'Ogun')], max_length=100),
        ),
    ]
